2025-07-04 16:25:12.352 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-07-04 16:25:12.353 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-07-04 16:25:12.354 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration viztron_drone which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-07-04 16:25:12.354 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration viztron_sentry which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-07-04 16:25:12.355 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration viztron_camera which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-07-07 04:26:06.813 ERROR (MainThread) [homeassistant.components.homeassistant_alerts.coordinator] Error requesting homeassistant_alerts data: Cannot connect to host alerts.home-assistant.io:443 ssl:default [Timeout while contacting DNS servers]
2025-07-08 02:15:39.269 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=45 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=45, family=2, type=2, proto=0, laddr=('0.0.0.0', 33988)>
2025-07-08 02:16:09.271 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=45 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=45, family=2, type=2, proto=0, laddr=('0.0.0.0', 33988)>
2025-07-08 02:16:09.272 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=41 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=41, family=10, type=2, proto=0, laddr=('::', 58940, 0, 0)>
2025-07-08 02:16:39.272 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=45 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=45, family=2, type=2, proto=0, laddr=('0.0.0.0', 33988)>
2025-07-08 02:16:39.273 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=41 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=41, family=10, type=2, proto=0, laddr=('::', 58940, 0, 0)>
2025-07-08 04:25:45.801 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'TimeoutError'
2025-07-08 04:25:45.802 ERROR (MainThread) [homeassistant.components.met.coordinator] Error fetching met data: Update failed: 
2025-07-08 21:03:21.006 WARNING (MainThread) [homeassistant.components.mqtt.client] Error returned from MQTT server: The connection was lost.
2025-07-08 21:18:19.997 WARNING (MainThread) [homeassistant.components.mqtt.client] Error returned from MQTT server: The connection was lost.
2025-07-08 21:33:55.736 WARNING (MainThread) [homeassistant.components.mqtt.client] Error returned from MQTT server: The connection was lost.
2025-07-08 21:41:47.704 WARNING (MainThread) [homeassistant.components.mqtt.client] Error returned from MQTT server: The connection was lost.
2025-07-08 21:42:55.366 WARNING (MainThread) [homeassistant.components.mqtt.client] Error returned from MQTT server: The connection was lost.
2025-07-08 21:43:28.831 WARNING (MainThread) [homeassistant.components.mqtt.client] Error returned from MQTT server: The connection was lost.
2025-07-08 21:44:49.108 WARNING (MainThread) [homeassistant.components.mqtt.client] Error returned from MQTT server: The connection was lost.
2025-07-08 21:44:59.855 WARNING (MainThread) [homeassistant.components.mqtt.client] Error returned from MQTT server: The connection was lost.
